drop table "Personal" cascade;
drop table "Enfermeros" cascade;
drop table "Medicos" cascade;
drop table "Pacientes" cascade;
drop table "Plantas" cascade;
drop table "Asignados" cascade;
drop table "Atendidos" cascade;
drop table "Diagnostico" cascade;
drop table "Ingresos" cascade;
