version: '3'
services: 
  postgres:
      image: postgres:latest
      restart: unless-stopped
      networks:
        appDjango:
          aliases:
            - database
      ports:
        - "5432:5432"
      environment:   # will be used by the init script
            LC_ALL: C.UTF-8
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: hospital
      volumes:
          - ./pgdata:/var/lib/postgresql/data/  
networks:
  appDjango:
